/*
** Copyright (C) 2014-2017 by Carnegie Mellon University.
**
** @OPENSOURCE_LICENSE_START@
** See license information in ../../LICENSE.txt
** @OPENSOURCE_LICENSE_END@
*/

/*
 *  skfixbuf.h
 *
 *    Simple wrapper over the header file from libfixbuf.h.
 */
#ifndef _SKFIXBUF_H
#define _SKFIXBUF_H
#include <silk/silk.h>

/* Define symbols to avoid avoid warnings generated by -Wundef */
#if !SK_HAVE_DECL_FB_ENABLE_SCTP
#define FB_ENABLE_SCTP 0
#endif
#if !SK_HAVE_DECL_HAVE_OPENSSL
#define HAVE_OPENSSL 0
#endif
#if !SK_HAVE_DECL_HAVE_SPREAD
#define HAVE_SPREAD 0
#endif

#include <fixbuf/public.h>

#endif /* _SKFIXBUF_H */

/*
** Local Variables:
** mode:c
** indent-tabs-mode:nil
** c-basic-offset:4
** End:
*/
